version: "3.8"

services:
  app:
    image: meyay/languagetool:latest
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
    security_opt:
      - no-new-privileges
    environment:
      download_ngrams_for_langs: de,en
      langtool_languageModel: /ngrams
    volumes:
      - app_ngrams:/ngrams
    networks:
      proxy_apps:

volumes:
  app_ngrams:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
